MINOR_ARCANA = {
    # Wands (Fire, creativity, action)
    "Ace of Wands": "Inspiration, new opportunities, growth.",
    "Two of Wands": "Planning, progress, making decisions.",
    "Three of Wands": "Expansion, foresight, overseas opportunities.",
    "Four of Wands": "Celebration, harmony, homecoming.",
    "Five of Wands": "Conflict, competition, tension.",
    "Six of Wands": "Victory, recognition, progress.",
    "Seven of Wands": "Perseverance, defense, maintaining control.",
    "Eight of Wands": "Swift action, movement, quick decisions.",
    "Nine of Wands": "Resilience, persistence, boundaries.",
    "Ten of Wands": "Burden, responsibility, hard work.",
    "Page of Wands": "Curiosity, enthusiasm, new ventures.",
    "Knight of Wands": "Adventure, energy, impulsiveness.",
    "Queen of Wands": "Confidence, independence, determination.",
    "King of Wands": "Leadership, vision, entrepreneurship.",

    # Cups (Water, emotions, relationships)
    "Ace of Cups": "Love, new relationships, emotional awakening.",
    "Two of Cups": "Partnership, unity, mutual attraction.",
    "Three of Cups": "Friendship, celebration, community.",
    "Four of Cups": "Apathy, contemplation, reevaluation.",
    "Five of Cups": "Loss, regret, focusing on the negative.",
    "Six of Cups": "Nostalgia, childhood memories, reconciliation.",
    "Seven of Cups": "Choices, illusions, wishful thinking.",
    "Eight of Cups": "Walking away, seeking deeper meaning.",
    "Nine of Cups": "Contentment, satisfaction, emotional fulfillment.",
    "Ten of Cups": "Harmony, happiness, emotional alignment.",
    "Page of Cups": "Innocence, creativity, emotional expression.",
    "Knight of Cups": "Romantic proposals, idealism, charm.",
    "Queen of Cups": "Compassion, intuition, emotional stability.",
    "King of Cups": "Emotional balance, wisdom, diplomacy.",

    # Swords (Air, intellect, conflict)
    "Ace of Swords": "Clarity, breakthroughs, new ideas.",
    "Two of Swords": "Difficult decisions, stalemate, indecision.",
    "Three of Swords": "Heartbreak, sorrow, grief.",
    "Four of Swords": "Rest, recovery, contemplation.",
    "Five of Swords": "Conflict, defeat, hollow victory.",
    "Six of Swords": "Transition, moving on, change.",
    "Seven of Swords": "Deception, strategy, hidden motives.",
    "Eight of Swords": "Restriction, fear, imprisonment.",
    "Nine of Swords": "Anxiety, nightmares, worry.",
    "Ten of Swords": "Betrayal, painful endings, rock bottom.",
    "Page of Swords": "Curiosity, vigilance, mental agility.",
    "Knight of Swords": "Ambition, fast-paced action, determination.",
    "Queen of Swords": "Independence, perception, clear communication.",
    "King of Swords": "Intellect, authority, truth.",

    # Pentacles (Earth, material wealth, career)
    "Ace of Pentacles": "New financial opportunities, prosperity.",
    "Two of Pentacles": "Balance, adaptability, time management.",
    "Three of Pentacles": "Collaboration, teamwork, skill development.",
    "Four of Pentacles": "Security, materialism, control.",
    "Five of Pentacles": "Financial loss, struggle, insecurity.",
    "Six of Pentacles": "Generosity, charity, financial support.",
    "Seven of Pentacles": "Patience, investment, long-term planning.",
    "Eight of Pentacles": "Diligence, craftsmanship, mastery.",
    "Nine of Pentacles": "Self-sufficiency, luxury, financial independence.",
    "Ten of Pentacles": "Legacy, wealth, long-term success.",
    "Page of Pentacles": "Ambition, learning, financial opportunities.",
    "Knight of Pentacles": "Hard work, responsibility, routine.",
    "Queen of Pentacles": "Nurturing, practicality, financial security.",
    "King of Pentacles": "Abundance, leadership, financial success."
}
